version: "3.7"

services:
  database:
    image: postgres
    container_name: fin_api_database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=fin_api
    volumes:
      - pgdata:/data/postgres
  app:
    restart: always
    build: .
    container_name: fin_api_app
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
